config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  get 'profiles', to: 'profiles#index' 
  get 'welcome/index'
  get 'alunos/new'
  get 'alunos/create'
  get 'alunos/show'
  get 'alunos/destroy'
  root 'welcome#index'
  get 'alunos/index', to: 'alunos#index'
  
  resources :alunos
  
  get '/cargos', to: 'cargos#index'
  get 'cargos/show'
  resources :cargos
  

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_create :generate_matricula_validation
  
  private
  def generate_matricula_validation
      self.matricula = (SecureRandom.random_number * (10**10)).round
  end
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    belongs_to :cargo, optional: true

    before_create :generate_matricula
    validates :aluno_name, :email, :cargo_id, presence: true
    validates :email, uniqueness: true, on: :create    
    before_save {self.email = email.downcase}
    before_save {self.aluno_name = aluno_name.titleize}
    

    private
    def generate_matricula
        self.matricula = (SecureRandom.random_number * (10**10)).round
    end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  has_many :users

  validates :funcao, :sigla, presence: true
  before_save { self.funcao = funcao.titleize }
  before_save { self.sigla = sigla.titleize }
  
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  before_create :generate_matricula
  # validates :profile_name, presence: true
   
  private
  def generate_matricula
      self.matricula = (SecureRandom.random_number * (10**10)).round
  end
         
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :cargo, optional: true

    before_create :generate_matricula
    validates :user_name, :email, :cargo_id, presence: true
    validates :email, uniqueness: true, on: :create    
    before_save {self.email = email.downcase}
    before_save {self.user_name = user_name.titleize}
    

    private
    def generate_matricula
        self.matricula = (SecureRandom.random_number * (10**10)).round
    end
    
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :authenticate_profile!  
  before_action :set_funcao_options, only: [:new, :create, :edit, :update]
  
  def index
    @alunos = Aluno.all
  end

  def new
    @aluno = Aluno.new
  end

  def edit
    @aluno = Aluno.find(params[:id])
  end
  
  def update
    @aluno = Aluno.find(params[:id])
    if @aluno.update(aluno_params)
      redirect_to alunos_path
    else
      render 'new'
    end
  end
  
  def create
    @aluno = Aluno.new(aluno_params)
    if @aluno != nil
      if @aluno.save
        redirect_to root_path
      else
        redirect_to new_aluno_path
      end
    else
      render 'new'
    end
  end


  def show
    @aluno = Aluno.find(params[:id])
  end

  def destroy
    @aluno = Aluno.find(params[:id])
    @aluno.destroy

    redirect_to alunos_path
  end

  private

    def set_funcao_options # esse metodo está sendo usado no _form.html.erb
      @funcao_options = Cargo.all.pluck(:funcao, :id)
    end

    def aluno_params
      params.require(:aluno).permit(:aluno_name, :email, :matricula, :cargo_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :authenticate_profile!
  # layout "adm"
  def index
    @cargos = Cargo.all
  end

  def show
    @cargo = Cargo.find(params[:id])
  end

  def new
    @cargo = Cargo.new
  end

  def create
    @cargo = Cargo.new(cargo_params)
    if @cargo.save
      redirect_to cargos_path
    else
      render 'new'
    end
  end
  
  def destroy
    @cargo = Cargo.find(params[:id])
    @cargo.destroy

    redirect_to cargos_path
  end
  

  private

  def cargo_params
    params.require(:cargo).permit(:funcao, :sigla)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    # before_action :teste

    def index
        @profiles = Profile.all
    end

    def show
        @profile = Profile.find(params[:id])
    end
    

    # protected
    # def teste
    #     devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_name])
    # end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
      <div id="error_explantion">
        <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this coin from being saved:</h2>
      <ul>
      <% aluno.aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>  
      </ul>
    </div>
  <% end %>
    <div>
      <%= form.label :aluno_name %><br>
      <%= form.text_field :aluno_name %>
    </div>
      <br>
    <div>
      <%= form.label :email %><br>
      <%= form.email_field :email%>
    </div>
      <br>
    <div>
      <%= form.label :funcao %>:
      <%= form.select("cargo_id", @funcao_options, { include_blank: 'Selecione...' }) %> 
     <br>
    </div>

    <div class="actions">
      <%= form.submit 'Salvar' %>
    </div>

<% end %>

app/views/alunos/create.html.erb
<h1>Novo Aluno</h1>

<%= form_with model: @aluno do |form| %>

<div>
  <%= form.label :aluno_name %><br>
  <%= form.text_field :aluno_name %>
</div>

<div>
  <%= form.label :email %><br>
  <%= form.email_field :email%>
</div>

<div class="actions">
  <%= form.submit 'Salvar' %>
</div>

<% end %>

app/views/alunos/edit.html.erb
<h1>Editar Usuário</h1>

<%= render "form", aluno: @aluno %>

<br>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Voltar', alunos_path %>

app/views/alunos/index.html.erb
<h1>Alunos</h1>

<table>
    <thead>
        <tr>
            <th>Name:</th>
            <th>E-mail:</th>
            <th>Matrícula:</th>
            <th>Ocupação:</th>
            <th colspan="4"></th>
        </tr>
    </thead>

    <tbody>
       <% @alunos.each do |aluno| %>
        <tr>
          <td><%= aluno.aluno_name %></td>
          <td><%= aluno.email %></td>
          <td><%= aluno.matricula %></td>
          <td><%= aluno.cargo.funcao %></td>
          <td><%= link_to 'Visualizar', aluno %></td>
          <td><%= link_to 'Editar', edit_aluno_path(aluno) %></td>
          <td><%= button_to 'Excluir', aluno, method: :delete, data: { confirm: 'Tem certeza'} %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New aluno', new_aluno_path %>
<%= link_to 'Cargos', cargos_path %>
<%#= link_to 'Sair', destroy_admin_session_path %>

app/views/alunos/new.html.erb
<h1>Novo Usuário</h1>

<%= render "form", aluno: @aluno %>

<br>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Voltar', alunos_path %>

app/views/alunos/show.html.erb
<h1><%= @aluno.aluno_name %></h1>

<p><strong>E-mail: </strong><%= @aluno.email %></p>
<p><strong>Matricula: </strong><%= @aluno.matricula %></p>
<p><strong>Função: </strong><%= @aluno.cargo.funcao %></p> 


<%= link_to 'Voltar', alunos_path %>
<%= link_to 'Editar', edit_aluno_path %>

app/views/cargos/index.html.erb
<h1>Cargos</h1>

<table>
 <thead>
     <tr>
        <th>Função: </th>
        <th>Sigla: </th>
        <th colspan="3"></th>
     </tr>
 </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.funcao %></td>
        <td><%= cargo.sigla %></td>
        <td><%= link_to 'Visualizar', cargo %></td>
        <td><%= button_to 'Excluir', cargo, method: :delete, data: { confirm: 'Tem certeza'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cargo', new_cargo_path %>
<%= link_to 'Voltar para Usuários', alunos_path %>
    

app/views/cargos/new.html.erb
<h1>Novo Cargo</h1>

<%= form_with model: @cargo do |form| %>

    <div>
        <%= form.label :funcao %><br>
        <%= form.text_field :funcao %>
    <div>

    <div>
        <%= form.label :sigla %><br>
        <%= form.text_field :sigla %>
    <div>

    <div class="actions">
        <%= form.submit 'Salvar' %>
        <%= link_to 'Voltar', cargos_path %>
    </div>
<% end %>

app/views/cargos/show.html.erb
<h1>Cargos</h1>

<p><strong>Ocupação: </strong> <%= @cargo.funcao %></p>
<p><strong>Sigla: </strong> <%= @cargo.sigla %></p>

<%= link_to 'Voltar', cargos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treinamentorails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text float-right">
    <% if profile_signed_in? %>
      Logado como: <strong><%= current_profile.email %></strong>.<br>
      Matricula: <strong><%#= current_profile.matricula %></strong>.
      <%= link_to 'Editar profile', edit_profile_registration_path, :class => 'navbar-link' %> |
      <%= button_to "Logout", destroy_profile_session_path, method: :delete, :class => 'navbar-link'  %> |
    <% else %>
      <%= link_to "Registrar-se", new_profile_registration_path, :class => 'navbar-link'  %> 
      <%= link_to "Login", new_profile_session_path, :class => 'navbar-link'  %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>Profiles</h1>

<table>
    <thead>
        <tr>
            <th>Name:</th>
            <th>E-mail:</th>
            <th>Matrícula:</th>
            <th>Ocupação:</th>
            <th colspan="4"></th>
        </tr>
    </thead>

    <tbody>
       <% @profiles.each do |profile| %>
        <tr>
          <td><%= profile.profile_name %></td>
          <td><%= profile.email %></td>
          <td><%= profile.matricula %></td>
          <td><%#= profile.cargo.funcao %></td>
          <td><%#= link_to 'Visualizar', profiles_path %></td>
          <td><%#= link_to 'Editar', edit_profile_path(profile) %></td>
          <td><%#= button_to 'Excluir', profile, method: :delete, data: { confirm: 'Tem certeza'} %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%#= link_to 'Novo Perfil', new_profile_registration_path %>
<%= link_to 'Cargos', cargos_path %>
<%#= link_to 'Sair', destroy_admin_session_path %>

app/views/profiles/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/profiles/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/create.html.erb
<h1>Novo Usuário</h1>

<%= form_with model: @user do |form| %>

<div>
  <%= form.label :user_name %><br>
  <%= form.text_field :user_name %>
</div>

<div>
  <%= form.label :email %><br>
  <%= form.email_field :email%>
</div>

<div class="actions">
  <%= form.submit 'Salvar' %>
</div>

<% end %>

app/views/welcome/index.html.erb
<h1>Bem vindo ao sistema de usuários</h1>
<p><%= link_to 'Usuários', alunos_index_path %> | <%= link_to 'Cargos', cargos_path %></p>